<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20140418 08:51:28.699" generator="Robot 2.8.4 (Python 2.6.6 on linux2)">
<suite source="/opt/robot/robotworkspace/robot_testsuites/experimental/mat/CRM/CRMUserActivation/activate.txt" id="s1" name="Activate">
<test id="s1-t1" name="Testcall1">
<kw type="kw" name="resource.Login To CRM">
<doc></doc>
<arguments>
</arguments>
<kw type="kw" name="Selenium2Library.Open Browser">
<doc>Opens a new browser instance to given URL.</doc>
<arguments>
<arg>${LOGIN URL}</arg>
<arg>${BROWSER}</arg>
</arguments>
<msg timestamp="20140418 08:51:28.993" level="INFO">Opening browser 'firefox' to base url 'http://10.0.20.17:1084/evoweb/web/crm/257_EN.htm'</msg>
<kw type="kw" name="Selenium2Library.Capture Page Screenshot">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<arguments>
</arguments>
<msg timestamp="20140418 08:51:30.243" level="FAIL">No browser is open</msg>
<status status="FAIL" endtime="20140418 08:51:30.243" starttime="20140418 08:51:30.240"></status>
</kw>
<msg timestamp="20140418 08:51:30.243" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open</msg>
<msg timestamp="20140418 08:51:30.244" level="FAIL">WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: no display specified\n' </msg>
<status status="FAIL" endtime="20140418 08:51:30.245" starttime="20140418 08:51:28.992"></status>
</kw>
<status status="FAIL" endtime="20140418 08:51:30.245" starttime="20140418 08:51:28.990"></status>
</kw>
<doc></doc>
<tags>
</tags>
<status status="FAIL" endtime="20140418 08:51:30.246" critical="yes" starttime="20140418 08:51:28.989">WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: no display specified\n' </status>
</test>
<doc>A test suite with a single test for valid login. This test has
a workflow that is created using keywords from the resource file.</doc>
<metadata>
</metadata>
<status status="FAIL" endtime="20140418 08:51:30.247" starttime="20140418 08:51:28.700"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" pass="0" id="s1" name="Activate">Activate</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20140418 08:51:28.984" level="ERROR">Error in file '/opt/robot/robotworkspace/robot_testsuites/experimental/mat/CRM/CRMUserActivation/resource.txt': Importing test library 'SSHLibrary' failed: AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/SSHLibrary/__init__.py", line 15, in &lt;module&gt;
    from .library import SSHLibrary
  File "/usr/lib/python2.6/site-packages/SSHLibrary/library.py", line 22, in &lt;module&gt;
    from .client import SSHClient
  File "/usr/lib/python2.6/site-packages/SSHLibrary/client.py", line 20, in &lt;module&gt;
    from pythonclient import PythonSSHClient as SSHClient
  File "/usr/lib/python2.6/site-packages/SSHLibrary/pythonclient.py", line 17, in &lt;module&gt;
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 31, in &lt;module&gt;
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 30, in &lt;module&gt;
    from paramiko import util
  File "/usr/lib/python2.6/site-packages/paramiko/util.py", line 34, in &lt;module&gt;
    from paramiko.common import DEBUG, zero_byte, xffffffff, max_byte
  File "/usr/lib/python2.6/site-packages/paramiko/common.py", line 129, in &lt;module&gt;
    from Crypto import Random
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in &lt;module&gt;
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in &lt;module&gt;
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in &lt;module&gt;
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in &lt;module&gt;
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in &lt;module&gt;
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
PYTHONPATH:
  /usr/lib/python2.6/site-packages/robot/libraries
  /usr/lib/python2.6/site-packages
  /usr/bin
  /usr/lib/python2.6/site-packages/robotframework_databaselibrary-0.6-py2.6.egg
  /usr/lib/python2.6/site-packages/psycopg2-2.4.6-py2.6-linux-x86_64.egg
  /usr/lib/python2.6/site-packages/ssh-1.8.0-py2.6.egg
  /usr/lib/python2.6/site-packages/decorator-3.4.0-py2.6.egg
  /usr/lib/python2.6/site-packages/robotframework_ride-1.1-py2.6.egg
  /usr/lib/python2.6/site-packages/Pygments-1.6-py2.6.egg
  /usr/lib/python2.6/site-packages/distribute-0.6.35-py2.6.egg
  /usr/lib/python2.6/site-packages/robotframework_selenium2library-1.5.0-py2.6.egg
  /usr/lib/python2.6/site-packages/selenium-2.41.0-py2.6.egg
  /usr/lib64/python26.zip
  /usr/lib64/python2.6
  /usr/lib64/python2.6/plat-linux2
  /usr/lib64/python2.6/lib-tk
  /usr/lib64/python2.6/lib-old
  /usr/lib64/python2.6/lib-dynload
  /usr/lib64/python2.6/site-packages
  /usr/lib64/python2.6/site-packages/gtk-2.0
  /usr/lib64/python2.6/site-packages/wx-2.8-gtk2-unicode
  .
  /opt/robot/robotworkspace/robot_testsuites/experimental/mat/CRM/CRMUserActivation</msg>
<msg timestamp="20140418 08:51:30.243" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open</msg>
</errors>
</robot>
